stages:
  - validate
  - sast
  - dast
  - test

sast:
  stage: sast
include:
- template: Security/SAST.gitlab-ci.yml
- template: Security/Dependency-Scanning.gitlab-ci.yml
- template: Security/Secret-Detection.gitlab-ci.yml
- template: DAST.gitlab-ci.yml

run tests:
  stage: validate
  image: python:3
  script:
    - pip install -r requirements.txt
    - mv DevOpsCustomerView/main/local.py.example DevOpsCustomerView/main/local.py 
    - echo "\nSECRET_KEY = 'test'" >> DevOpsCustomerView/main/local.py
    - pytest --cov DevOpsCustomerView/ DevOpsCustomerView/userinterface/tests --junitxml=report.xml
    - coverage report
    - coverage xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    when: always
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
